### ISSUE TITLE
[Feat] : 구매 상세 페이지 기본 틀 구축

### ISSUE THREAD

**Issue by arinming** [donga-st-b/frontend#11]
## 설명
구매 상세 페이지 기본 틀을 구축합니다.

## To-Do List
- [x] 헤더, 상세 제품 표시, 설명 메뉴, 푸터 순으로 위치
- [x] 이미지, 아이콘 불러오기
- [x] 텍스트 박스, 메뉴 그룹, 버튼 컴포넌트 구현
