### ISSUE TITLE
[Feat] : 메인 페이지 컴포넌트 1-3 구현

### ISSUE THREAD

**Issue by arinming** [DONGA-ST-B/frontend#22]
## 설명
메인 페이지의 컴포넌트를 1부터 3까지 구현합니다.

## To-Do List
- [x] 메인 페이지 기본 툴 구축
- [x] 배너 동영상 구현
- [x] 하이카디 활용 사례
- [x] 왜 하이카디를 선택해야 하나요?
