### ISSUE TITLE
[Feat] : 메인 페이지 컴포넌트 4-5 구현

### ISSUE THREAD

**Issue by chamny20** [donga-st-b/frontend#26]
## 설명
메인 페이지 컴포넌트 view4~5 구현

## To-Do List
- [ ] component4 UI 개발
- [ ] apply interaction in component4
- [ ] component5 UI 개발
- [ ] apply interaction in component5
- [ ] load API data in component5
