### ISSUE TITLE
[Feat] : 구매 리스트 페이지의 제품 리스트를 구체적으로 구현

### ISSUE THREAD

**Issue by arinming** [donga-st-b/frontend#6]
## 설명
기본적인 툴만 구현해놓은 제품 리스트를 구체적으로 구현합니다.

## To-Do List
- [x] 제품 하나의 컴포넌트 구현
- [x] 제품 클릭 이벤트 구현
- [x] Figma의 디자인에 맞도록 전체적인 구현
